Repository realtime-cinema/realtime-cinema, pull requests merged in 2024-04, with the labels that each got.

#1 new feauter! merge giup bo m
  src/app/pickseat/components/Chair.tsx
Labels: bug, documentation, duplicate

#3 FIX BUG
  next.config.js
  src/app/book/components/dateUtils.js
  src/app/book/components/get-day.tsx
  src/types/global.d.ts
Labels: bug

#4 Feature vip
  package-lock.json
  package.json
  public/avt10.jpg
  public/avt3.jpg
  public/avt4.jpg
  public/avt5.jpg
  public/avt6.jpg
  public/avt7.jpg
  public/avt8.jpg
  public/avt9.jpg
  public/bg.jpg
  public/bg1.jpg
  public/pinkAccumulation.svg
  public/playButton.svg
  src/app/film/[filmID]/components/Comment.tsx
  src/app/film/[filmID]/components/ComponentData.tsx
  src/app/film/[filmID]/components/Poster.tsx
  src/app/film/[filmID]/components/UserComment.tsx
  src/app/film/[filmID]/page.tsx
  src/app/film/components/ComponentData.tsx
  src/app/film/components/PosterFilm.tsx
  src/app/film/components/filmDangChieu.tsx
  src/app/film/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  tailwind.config.js
  yarn.lock
Labels: enhancement
